### ISSUE TITLE
Replacing trailing bullets by UTF-8 bullets

### ISSUE THREAD

**Issue by sorganov** [integral-dw/org-superstar-mode#15]
Hello,

I'm a new user or org-superstar running MELPA Version 20200416.2354 on top of org version 9.3 and Emacs snapshot 28.0.50.

I'd like to replace trailing dots (...) at the end of headlines of collapsed sections by something more pleasant, and I thought that maybe "replacing trailing bullets by UTF-8 bullets" is the feature I need. However,  I don't see any replacement happening, nor am I able to find any relevant customization or even code in the `org-superstar.el`.  

What do I miss?

As a side-note, as far as I can tell, the "Installation" instructions could be reduced to:

```elisp
(require 'org-superstar)
(add-hook 'org-mode-hook 'org-superstar-mode)
```

No lambda needed, as org-superstar-mode "If called from Lisp, also enable the mode if ARG is omitted or nil,..."

**Comment by dakra** [comment]
org-superstar doesn't handle those trailing dots.
You probably want to customize `org-elipsis`.
I have this in my config
``` emacs-lisp
  ;; Insead of "..." show "…" when there's hidden folded content
  ;; Some characters to choose from: …, ⤵, ▼, ↴, ⬎, ⤷, and ⋱
  (setq org-ellipsis "…")
```

**Comment by sorganov** [comment]
Ah, thanks a lot! I'm closing the issue then.
