### ISSUE TITLE
Not seeing all options to customize / superfluous interactive command

### ISSUE THREAD

**Issue by Arjay-El** [integral-dw/org-superstar-mode#16]
WIN10 user, Emacs 26.3, Scimax customization:

I loaded org-superstar via Melpa but I only see these options listed when called up via ALT-x.
org-superstar-mode
org-superstar-restart
org-superstar-headline-p
org-superstar-toggle-lightweight-lists

I dont see any of the other options to list/edit/cycle the bullets used as stated in the readme. Is there something I missed or is it a Win10 thing?

Thanks

**Comment by integral-dw** [comment]
Hi @Arjay-El,
The options you see using Alt-x (commonly referred to as `M-x`) are the **interactive commands** available to you whilst editing.  Funnily enough, `org-superstar-headline-p` should not even *be* interactive, that is just an oversight from old debugging days.  Thanks for pointing it out!  The options described in the README are accessible to you largely via the Emacs' custom interface as well as via Emacs Lisp scripting (editing your .emacs).  If you need further pointers, be sure to ask.
