### ISSUE TITLE
Setting org-superstar-remove-leading-stars to t breaks some built-in org movement commands.

### ISSUE THREAD

**Issue by mjkalyan** [integral-dw/org-superstar-mode#19]
I recently discovered that setting `(setq org-superstar-remove-leading-stars t)` makes the `org-{forward,backward}-heading-same-level`command ineffectual when the cursor is hovering on a subheading. However, those commands will work as intended on top level headings - presumably because there is nothing for `org-superstar-remove-leading-stars` to do on such headings.

I'm using GNU Emacs 26.3.

**Comment by integral-dw** [comment]
Hi, I'll have to look into this in greater detail, but it stems from the fact that org realizes that the heading is partially invisible, but not that it's not entirely invisible, leading to some inconsistent behavior.  That is why the functions seem to work if their optional second argument is non-nil.  So in other words, this hack seems to work as expected 
``` emacs-lisp
(defun my-forward-heading-same-level (arg)
  (interactive "p")
  (org-forward-heading-same-level arg t))
(defun my-backward-heading-same-level (arg)
  (interactive "p")
  (org-backward-heading-same-level arg t))
```
I'll have to mull over this a bit and most likely contact the mailing list to come up with the least intrusive solution to this.

**Comment by integral-dw** [comment]
Quick update: I fixed up a patch for org-mode to take care of the issue, and it will most likely find its way upstream some time the coming week.  It looks like no code change will be necessary on this end.

**Comment by mjkalyan** [comment]
Thank you! I'll continue using your work around code in the meantime.

**Comment by integral-dw** [comment]
The [patch](https://code.orgmode.org/bzg/org-mode/commit/a700fadd72ad7166d3815a368f487fe8dfe51fef) has been accepted!
