### ISSUE TITLE
Not all bullets are displayed correctly

### ISSUE THREAD

**Issue by noaccOS** [integral-dw/org-superstar-mode#26]
![image](https://user-images.githubusercontent.com/24324352/108438798-4bd2fa00-7250-11eb-8d6f-588290dda21a.png)
Title.
Only some of the top level bullets are displayed, usually they are always the same at startup but with a restart some other top level might get displayed and others don't.
It only happens with this set of bullets (U+1F7C1-8 tested, from the link "Geometric shapes extended" in the readme), but not with the other commented one.

When starting with the offending bullets, there are some error messages
![image](https://user-images.githubusercontent.com/24324352/108439101-ec291e80-7250-11eb-860a-3e48e6d3dc25.png)

I'm using the latest emacs-git version

**Comment by integral-dw** [comment]
Hi @noaccOS, your list has commas, which is not syntactically valid in Elisp.
Try `(a b c)` instead of `(a, b, c)`, where a,b,c would be your strings.

**Comment by noaccOS** [comment]
I feel dumb, thank you and sorry

**Comment by integral-dw** [comment]
I had a day-long discussion the other day until I realized I completely missed the point, things happen.
