### ISSUE TITLE
Replace the TODO and DONE keywords with unicode?

### ISSUE THREAD

**Issue by linwaytin** [integral-dw/org-superstar-mode#32]
Thanks for this great package, which makes org-mode appear like other fancy todo manager.
For now I use `org-superstar-special-todo-items` option to make the leading stars become a checkbox depending on TODO and DONE keywords.
Is there a way to keep the leading stars and replace the TODO and DONE keywords with the checkbox?
For example, instead of 
☑ DONE
I would like to have 
♠ ☑,
where ♠ is the bullet replacing the leading star.

**Comment by thibautbenjamin** [comment]
You don't need the `org-superstar-special-todo-items` for that, just use the regular org-superstar configuration and add
```
    (push '("TODO" . "☐") prettify-symbols-alist)
    (push '("DONE" . "☑") prettify-symbols-alist)
    (prettify-symbols-mode)
```
as a hook for org-mode

**Comment by linwaytin** [comment]
Thanks, that works!
