### ISSUE TITLE
Disable heading superstar

### ISSUE THREAD

**Issue by Inc0n** [integral-dw/org-superstar-mode#36]
I have recently starting to use `org-bars`, which adds its own heading bullets to org headings, but I still want to keep the bullet list prettifying from `org-superstar`.

I tried setting `org-superstar-headline-bullets-list` to nil but that just made all the heading bullets disappear.

Please add this feature, where we can disable heading bullets prettifying.

**Comment by integral-dw** [comment]
I added a new option to `org-superstar-special-todo-items`, setting it to the symbol `only` should now do exactly what you want.
