### ISSUE TITLE
The modeline string doesn't render correctly

### ISSUE THREAD

**Issue by lmintmate** [integral-dw/org-superstar-mode#4]
When org-superstar-mode is enabled, and no other modeline modifiers (e.g. minor mode hiders, like [minions](https://github.com/tarsius/minions), or modeline beautifiers, such as [all-the-icons](https://github.com/domtronn/all-the-icons.el) or [emojify](https://github.com/iqbalansari/emacs-emojify)) are installed/enabled, the modeline string (which is supposed to be a fancy star, as I can see from the source code, as rendered on Github), is either rendered as a tofu block (on my Windows 10 system - top picture, Courier being, it seems, the default font) or so badly as to be barely visible (on my Linux system - bottom picture, DejaVu Sans Mono being the default font).
![org-superstar-modeline-problem-windows](https://user-images.githubusercontent.com/26282842/76077370-403be400-5fa9-11ea-8323-3dbb6853728d.PNG)
![org-superstar-modeline-problem-linux](https://user-images.githubusercontent.com/26282842/76078002-7463d480-5faa-11ea-8b37-7766a9486cf6.png)
To solve this, I'd suggest using instead either plain text (like the mode name - this might be a somewhat long string, but that's what packages like minions are for) or nothing at all (which won't display anything on the mode line, probably not as good for transparency).
Thanks in advance for your consideration.
P.S. Interestingly, when clicking on the modeline string, the icon on the popup menu has a better appearance on Windows 10,
![org-superstar-modeline-problem-windows-2](https://user-images.githubusercontent.com/26282842/76079176-cdcd0300-5fac-11ea-83fc-64018dcebb17.PNG)
but not on Linux.
![org-superstar-modeline-problem-linux2](https://user-images.githubusercontent.com/26282842/76079420-49c74b00-5fad-11ea-8a5b-f03ec8c0947b.png)

**Comment by integral-dw** [comment]
Hi,

I see! I'm using DejaVu Sans myself, but it seems my increased default text height makes it look nicer than it otherwise would have.  Given the fact that the minor mode has no menu to speak of, I'll just throw it out.

**Comment by lmintmate** [comment]
> Hi,
> 
> I see! I'm using DejaVu Sans myself, but it seems my increased default text height makes it look nicer than it otherwise would have. Given the fact that the minor mode has no menu to speak of, I'll just throw it out.

I also use an increased font size in my default config, but lately since I was experimenting on and off with org-superstar and some other packages not on MELPA, I have an alternative config on a different folder of my Windows 10 pc and frequently swap them out. On that alternative config, which also has the increased font size, I don't have installed several packages from my normal config, among them minions. I thus first saw the tofu box effect I posted a picture of on that config first, but hadn't paid it much mind until today, when I finally thought to click on it to see what was causing it, and saw it was from org-superstar.
P.S. In fact, here is how it looks like on that config:
![org-superstar-modeline-problem-windows-half-config PNG](https://user-images.githubusercontent.com/26282842/76116587-efe97400-5ff2-11ea-9421-5a604bf58d3e.jpg)
(the popup menu looks the same though). So even if it looked fine on Linux, it probably wouldn't on Windows anyways, so thanks for fixing that.

**Comment by integral-dw** [comment]
Always glad to help!
