### ISSUE TITLE
Readme not correct.

### ISSUE THREAD

**Issue by ghost** [integral-dw/org-superstar-mode#45]
The readme says that I just need to type this for config:

```
(require 'org-superstar)
(add-hook 'org-mode-hook (lambda () (org-superstar-mode 1)))
```

I did that, but it does NOT automatically enable org-superstar-mode when org-mode gets activated, I have to enable it manually every time.

Any ideas?

**Comment by integral-dw** [comment]
Hi @ghost, 
I was not able to reproduce your problem as the above works flawlessly with `emacs --no-init`, so it is most likely that there is an issue with your `.emacs`.
