### ISSUE TITLE
Wrong bullet rendering with Iosevka

### ISSUE THREAD

**Issue by mrusso99** [integral-dw/org-superstar-mode#46]
I have some strange issues with Iosevka, when i render headings there is no spacing

![org-bug](https://user-images.githubusercontent.com/28223818/206865490-d1e08772-c4dc-4cc0-a64c-dff71282fe86.png)

But with another font (like inconsolata) org-superstar works properly 

![org-bug-working](https://user-images.githubusercontent.com/28223818/206865491-a8cbc753-6826-47ba-9c13-a29c6173862a.png)

**Comment by integral-dw** [comment]
Hi,

I did not manage to reproduce the issue using Iosevka Regular. Could you try boiling down your init to a minimum working example, or provide a more detailed description of how to reproduce the issue starting from `emacs --no-init`?

**Comment by mrusso99** [comment]
Unfortunately i can't reproduce it either, i used NixOS at the time and with the same config on different distros  i noticed that the issue was not present (both arm and x64).

**Comment by integral-dw** [comment]
Alright, thank you for clarifying!
