### ISSUE TITLE
Is this a replacement for org-bullets? 

### ISSUE THREAD

**Issue by ema2159** [integral-dw/org-superstar-mode#7]
That would be really awesome since org bullets is no longer maintained.

**Comment by alphapapa** [comment]
> Prettify headings and plain lists in Org mode. This package is a direct descendant of ‘org-bullets’, with most of the code base completely rewritten

**Comment by ema2159** [comment]
@alphapapa it seems I missed that part. Thank you! Replacing org-bullets right away!
