### ISSUE TITLE
Testing org-superstar with older emacs and org versions

### ISSUE THREAD

**Issue by lmintmate** [integral-dw/org-superstar-mode#8]
As stated in the discussion [here](https://github.com/melpa/melpa/issues/6748), the current requirements of org-superstar, that is emacs 26.2 and org 9.1.9, are simply what @integral-dw had available for testing. Given that, it seems imperative to test for older emacs and org versions in case org-superstar _can_ work on these without adding any compatibility workarounds. I decided to take it up on myself, to make sure that it will happen. The method I've thought of so far is using the zip file releases of emacs on Windows 10, which will allow me to keep my existing emacs install and also run many other versions on the same machine (if there is a better method, please let me know), and using a minimal init file only installing and enabling org-superstar.
The versions I'll be testing for are:
- emacs 24.3 (probably optionally, this might be considered too old)
- emacs 25.1
- emacs 25.2
- emacs 25.3
- emacs 26.1
and their accompanying org versions, most older than the current requirement. (26.2 and 26.3 are already covered given the package requirement).
I'm planning to test opening an org file with org-superstar enabled, and turning org-superstar off and on again while still in the file, and maybe also change a setting that would require me to run `org-superstar-restart`. If there is anything else I should test for please let me know.
I'll update here once I'm certain with my conclusions (this won't take too long, as I already started testing and it's quicker than I expected).

**Comment by lmintmate** [comment]
Observations of the testing:

I wasn't able to install org-superstar via melpa, as it complained that package 'emacs 26.2' is unavailable and doesn't install the package (obviously because it read the header requirements and stopped there). I thus added the .el file to a folder in the load path.

emacs 24.3 (with default org version 7.9.3f) is completely off the table, as while it may have loaded fine at first (probably because it wasn't exactly loaded as a package, but via the load-path), when I try to disable it and again when I re-enable it, it complains that `Symbol's function definition is void: font-lock-ensure`. This is a main emacs function, and it was probably added on emacs 25+. I also wasn't able to install the latest org mode version on that one.

emacs 25.1 and 25.2, when using the default org version 8.2.10, worked fine when I first loaded the org file, but when trying to use `org-superstar-restart` or disabling and enabling again `org-superstar-mode` I get: `Symbol's function definition is void: org-element-lineage`. This seems (looking at the docstring in the current org mode version) to have been added in org 9.0 and later. Indeed when I installed the latest org mode version on these emacs versions (9.3.6 at the time of this writing) I got no complaints and the package worked just fine.

emacs 26.1 has as default org version 9.1.9, and thus works fine from the start.

Bizzarely enough, however, while emacs 25.1 and 25.2 work fine with the latest version of org-mode installed, 25.3 presents some peculiarities, regardless of the org version installed (though when using 8.2.10 instead of the latest, there is additionally the complaint about org-element-lineage). In particular, the first level of org stars show as boxes instead of fisheyes and they are also rendered greyed out next to the level 2 and 3, which are rendered fine. Here are the relevant illustrations:
Shows as normal in emacs 25.1:
![25-1 normal](https://user-images.githubusercontent.com/26282842/76679236-7f8cb500-65e7-11ea-9b60-74b3b7ef641e.jpg)
Here's how it shows on emacs 25.3:
![25-3 peculiarity](https://user-images.githubusercontent.com/26282842/76679245-8ddad100-65e7-11ea-97a5-b1aec74ce3cc.jpg)
I have no idea what could be causing this, and should probably investigate further.

Conclusions:
With the exception of emacs 25.3 peculiarities, org-superstar works fine with the latest org mode version on emacs 25+ (25.1 and 25.2), and also obviously on 26.1 with default org mode version 9.1.9 (if I had a way of testing 9+ org mode versions prior to 9.1.9, I would do so, but I don't know how I would get these versions). The requirement of org-mode version 9+/9.1.9 has to remain because of the presence of org-element-lineage in the code, but the emacs version could be safely lowered to 25.1 if it weren't for the peculiarites of 25.3. Right now, it still can be safely lowered to 26.1 until I manage to figure out what causes the peculiarities of 25.3.

**Comment by integral-dw** [comment]
Thanks for testing! I will update the Emacs version requirement to 26.1 in the upcoming version __1.1.0__, see the `volatile` branch.

**Comment by integral-dw** [comment]
Hello, I am the current maintainer of this package (more accurately, the version available on MELPA).
Sadly I fail to reproduce this issue. Should it persist, be sure to open an issue [here](https://github.com/integral-dw/org-bullets).

**Comment by integral-dw** [comment]
(I know you already know that, but I thought it's best to just reply to all such issues the same way :sweat_smile: )
